apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: db-sync-hpa
  namespace: cardano
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cardano-db-sync
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80