apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardano-db-sync
  namespace: cardano
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardano-db-sync
  template:
    metadata:
      labels:
        app: cardano-db-sync
    spec:
      containers:
      - name: db-sync
        image: ghcr.io/intersectmbo/cardano-db-sync:13.6.0.4
        # get from https://github.com/intersectmbo/cardano-db-sync/pkgs/container/cardano-db-sync
        env:
        - name: DB_SYNC_DB
          valueFrom:
            secretKeyRef:
              name: postgresql-secrets
              key: POSTGRES_DB
        - name: DB_SYNC_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secrets
              key: POSTGRES_USER
        - name: DB_SYNC_PASS
          valueFrom:
            secretKeyRef:
              name: postgresql-secrets
              key: POSTGRES_PASSWORD
        - name: PGPASSFILE
          value: /tmp/pgpass-mainnet

        # run command: https://github.com/IntersectMBO/cardano-db-sync/blob/master/doc/running.md

        # command:
        # - "find"
        # - "/"
        # - "-name"
        # - "db-sync-config.json"

        # - "tail"
        # - "-f"
        # - "/config/db-sync-config.json"

        command: ["/bin/sh", "-c"]
        args:
        - |
          # Pass variables
          cp /config/pgpass-mainnet /tmp/pgpass-mainnet
          sed -i "s/POSTGRES_DB/$DB_SYNC_DB/g" /tmp/pgpass-mainnet
          sed -i "s/POSTGRES_USER/$DB_SYNC_USER/g" /tmp/pgpass-mainnet
          sed -i "s/POSTGRES_PASSWORD/$DB_SYNC_PASS/g" /tmp/pgpass-mainnet
          chmod 0600 /tmp/pgpass-mainnet
          # Run
          cardano-db-sync \
            --config /config/db-sync-config.json \
            --socket-path /config/node.socket \
            --state-dir /root/src/cardano-environments/mainnet/ledger-state \
            --schema-dir /nix/store/s7vh6jy8gibyrrqkkhvcazkcmflvv45k-schema/

        volumeMounts:
        - name: config
          mountPath: /config
        resources:
          requests:
            cpu: "0.5"
            memory: "2Gi"
          limits:
            cpu: "1"
            memory: "4Gi"
      volumes:
      - name: config
        configMap:
          name: cardano-db-sync-config