apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cardano-node
  namespace: cardano
spec:
  serviceName: cardano-node
  replicas: 1
  selector:
    matchLabels:
      app: cardano-node
  template:
    metadata:
      labels:
        app: cardano-node
    spec:
      initContainers:
      - name: mithril-client
        image: blinklabs/mithril-client:latest
        env:
        - name: AGGREGATOR_ENDPOINT
          value: https://aggregator.release-mainnet.api.mithril.network/aggregator
        - name: GENESIS_VERIFICATION_KEY
          value: 5b3139312c36362c3134302c3138352c3133382c31312c3233372c3230372c3235302c3134342c32372c322c3138382c33302c31322c38312c3135352c3230342c31302c3137392c37352c32332c3133382c3139362c3231372c352c31342c32302c35372c37392c33392c3137365d
        - name: SNAPSHOT_DIGEST
          value: latest
        command:
        # - "tail"
        # - "-f"
        # - "/dev/null"

        - "echo"
        - "abc"
        - ">"
        - "/dev/null"

        # mithril-client -v --aggregator-endpoint https://aggregator.release-mainnet.api.mithril.network/aggregator cardano-db download latest

        volumeMounts:
        - name: node-data
          mountPath: /data
      containers:
      - name: cardano-node
        image: ghcr.io/intersectmbo/cardano-node:10.1.4
        # get from https://github.com/IntersectMBO/cardano-node/releases
        command:
        # - "tail"
        # - "-f"
        # - "/dev/null"

        - "cardano-node"
        - "run"
        - "--config"
        - "/config/testnet-config.json"
        - "--topology"
        - "/config/testnet-topology.json"
        - "--host-addr"
        - "0.0.0.0"
        - "--port"
        - "3001"

        ports:
        - containerPort: 3001
        volumeMounts:
        - name: node-data
          mountPath: /data
        - name: config
          mountPath: /config
        resources:
          requests:
            cpu: "0.5"
            memory: "2Gi"
          limits:
            cpu: "1"
            memory: "4Gi"
      volumes:
      - name: config
        configMap:
          name: cardano-node-config
  volumeClaimTemplates:
  - metadata:
      name: node-data
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 100Gi