apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cardano-node-pvc
  namespace: cardano
spec:
  accessModes:
    - ReadWriteMany  # Requires shared storage backend
  resources:
    requests:
      storage: 10Gi
